version: "3"
services:
  2fauth:
    env_file:
      - .env
    image: 2fauth/2fauth
    container_name: 2fauth
    volumes:
      - 2fauth:/2fauth
    ports:
      - 8000:8000/tcp
    restart: always
volumes:
   2fauth:
