apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webserverService.metadata.name}}
  namespace: {{ .Values.webserverService.metadata.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.webserverService.spec.selector.app}}
  ports:
    - port: {{ .Values.webserverService.port}}
      targetPort: {{ .Values.webserverService.targetPort}}