version: '3'

# networks
# create a network 'guacnetwork' in mode 'bridged'
networks:                                                                            
  guacnetwork:                                                                         
    driver: bridge

# services
services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      guacnetwork:
    restart: always
    volumes:
    - drive:/drive:rw
    - record:/record:rw

  mariadb:
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_USER_FILE=/run/secrets/mysql_user
    image: linuxserver/mariadb:alpine
    networks:
      guacnetwork:
    restart: always
    volumes:
      - mariadb:/config
    secrets:
      - mysql_root_password
      - mysql_password
      - mysql_database
      - mysql_user

  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - mariadb
    environment:
      - GUACD_HOSTNAME=${GUACD_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - TOTP_ENABLED=${TOTP_ENABLED}
      - GUACAMOLE_HOME=${GUACAMOLE_HOME}
    secrets:
      - mysql_database
    volumes:
    - home:/etc/guacamole
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacnetwork:
    ports:
## enable next line if not using nginx
    - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
## enable next line when using nginx
##    - 8080/tcp
    restart: always

volumes:
 drive:
 record:
 mariadb:
 home:
 
secrets:
  mysql_root_password:
    file: ./Secrets/mysql_root_password.txt
  mysql_password:
    file: ./Secrets/mysql_password.txt
  mysql_database:
    file: ./Secrets/mysql_database.txt
  mysql_user:
    file: ./Secrets/mysql_user.txt
