apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: webapp
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: http-webserver