version: "3.5"
services: 
  AdGuard: 
    image: adguard/adguardhome
    volumes:
      - config:/opt/adguardhome/conf
      - data:/opt/adguardhome/work
    ports: 
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "3000:3000/tcp"
    restart: always
volumes: 
  config:
  data: